In [ ]:
from google.colab import files
files.upload()  # Yüklədiyiniz kaggle.json faylını seçin

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"mehemmedhaciyev","key":"38713a17258cfda4d7a1f05214804bc0"}'}

In [ ]:
import os
os.makedirs('/root/.kaggle', exist_ok=True)
os.rename('kaggle.json', '/root/.kaggle/kaggle.json')

In [ ]:
!kaggle datasets download -d <dataset-name>

/bin/bash: -c: line 1: syntax error near unexpected token `newline'
/bin/bash: -c: line 1: `kaggle datasets download -d <dataset-name>'

In [ ]:
! kaggle datasets download sehriyarmemmedli/turboaz-cars-project

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /root/.kaggle/kaggle.json'
Dataset URL: https://www.kaggle.com/datasets/sehriyarmemmedli/turboaz-cars-project
License(s): unknown
turboaz-cars-project.zip: Skipping, found more recently modified local copy (use --force to force download)

In [ ]:
! unzip '/content/turboaz-cars-project.zip'

Archive:  /content/turboaz-cars-project.zip
replace cars.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: cars.csv

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Data Cleaning

In [ ]:
df = pd.read_csv('/content/cars.csv')
df.head()

,id_x,car_rel_url_x,datetime_scrape,name,price_x,currency_x,datetime_product,city,day,hour,...,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Yürüş,Ötürücü,Şəhər,car_details_id_y,car_rel_url,extra_info
0,3c234145-d57a-4ad6-9448-d43810fc3392,/autos/8748840-hyundai-i30,2024-09-13 20:32:19.751157+00,Hyundai i30,15000.0,AZN,"Bakı, dünən 23:28",bakı,13.09.2024,23:28,...,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,270 000 km,Ön,Bakı,8d84d800-fafd-4d5c-b640-f47bd6c5ac20,/autos/8748840-hyundai-i30,Yüngül lehimli disklər* ABS* Mərkəzi qapanma* ...
1,c74ea36f-6be1-4de4-926d-e117197dcf00,/autos/8475807-lada-vaz-niva-travel,2024-09-13 20:32:19.751157+00,LADA (VAZ) Niva Travel,23700.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5,0 km,Tam,Bakı,2cf8b84b-adaf-467a-8f06-3dabcf866c8a,/autos/8475807-lada-vaz-niva-travel,Yüngül lehimli disklər* ABS* Kondisioner* Otur...
2,9cefceb0-024d-4581-a869-a3c2c68a9f95,/autos/8739686-toyota-land-cruiser,2024-09-13 20:32:19.751157+00,Toyota Land Cruiser,35600.0,$,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8+,164 750 km,Tam,Bakı,22bb3704-ebe7-4357-ba2f-1806d1a7042b,/autos/8739686-toyota-land-cruiser,Yüngül lehimli disklər* ABS* Lyuk* Mərkəzi qap...
3,459cc337-fb63-48de-9694-41554923d311,/autos/8712597-hyundai-elantra,2024-09-13 20:32:19.751157+00,Hyundai Elantra,26700.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,126 000 km,Ön,Bakı,e0d16dac-4091-4417-916e-cadeff600f95,/autos/8712597-hyundai-elantra,Yüngül lehimli disklər* ABS* Lyuk* Yağış senso...
4,6c5ee8d8-1c6f-4fad-a694-957a4c43c25d,/autos/8674773-toyota-prius,2024-09-13 20:32:19.751157+00,Toyota Prius,10500.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,354 000 km,Ön,Bakı,82078856-0d07-4a0d-8123-69c2e5002e07,/autos/8674773-toyota-prius,Arxa görüntü kamerası

In [ ]:
df.describe()

,price_x,production_year,engine_displacement_num,kilometrage_num,price_y,phone,views,Buraxılış ili
count,653721.000000,653721.000000,653721.000000,6.537210e+05,653721.000000,6.534560e+05,653721.000000,653721.000000
mean,31630.966437,1995.886897,2.221417,1.565231e+05,31630.917933,5.589415e+08,3740.731827,2013.797752
std,28679.360855,188.793547,1.266334,1.458949e+05,28679.394420,1.516718e+08,10299.032842,7.646318
min,500.000000,0.000000,0.000000,0.000000e+00,500.000000,7.800000e+01,12.000000,1938.000000
25%,16800.000000,2009.000000,1.600000,5.502200e+04,16800.000000,5.060014e+08,432.000000,2009.000000
50%,25300.000000,2015.000000,2.000000,1.450000e+05,25300.000000,5.524029e+08,1367.000000,2015.000000
75%,36800.000000,2019.000000,2.500000,2.223330e+05,36800.000000,5.588827e+08,3412.000000,2019.000000
max,940000.000000,2024.000000,120.000000,9.900025e+06,940000.000000,9.999997e+08,359317.000000,2024.000000

In [ ]:
df['production_year']

0         2008
1         2024
2         2011
3         2018
4         2007
          ...
653716    2008
653717    2011
653718    2018
653719    1999
653720    2023
Name: production_year, Length: 653721, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 653721 entries, 0 to 653720
Data columns (total 56 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_x                      653721 non-null  object
 1   car_rel_url_x             653721 non-null  object
 2   datetime_scrape           653721 non-null  object
 3   name                      653721 non-null  object
 4   price_x                   653721 non-null  float64
 5   currency_x                653721 non-null  object
 6   datetime_product          653721 non-null  object
 7   city                      653721 non-null  object
 8   day                       653721 non-null  object
 9   hour                      653721 non-null  object
 10  attributes                653721 non-null  object
 11  production_year           653721 non-null  int64
 12  engine_displacement_num   653721 non-null  float64
 13  engine_displacement_unit  647933 non-null  object
 14  kilometrage_num           653721 non-null  int64
 15  kilometrage_unit          647933 non-null  object
 16  barter                    225553 non-null  object
 17  loan                      163340 non-null  object
 18  salon                     193339 non-null  object
 19  spare_parts               1762 non-null    object
 20  vip                       288941 non-null  object
 21  featured                  163835 non-null  object
 22  img_url                   653721 non-null  object
 23  id_y                      653721 non-null  object
 24  cars_id                   653721 non-null  object
 25  car_rel_url_y             653721 non-null  object
 26  datetime                  653721 non-null  object
 27  description               638192 non-null  object
 28  price_y                   653721 non-null  float64
 29  currency_y                653721 non-null  object
 30  owner_name                453496 non-null  object
 31  shop_name                 199960 non-null  object
 32  phone                     653456 non-null  float64
 33  updated                   653721 non-null  object
 34  views                     653721 non-null  int64
 35  vin                       44271 non-null   object
 36  car_details_id_x          653721 non-null  object
 37  Ban növü                  653721 non-null  object
 38  Buraxılış ili             653721 non-null  int64
 39  Hansı bazar üçün yığılıb  464216 non-null  object
 40  Marka                     653721 non-null  object
 41  Model                     653720 non-null  object
 42  Mühərrik                  653721 non-null  object
 43  Qəzalı                    1761 non-null    object
 44  Rəng                      653721 non-null  object
 45  Sahiblər                  432100 non-null  object
 46  Sürətlər qutusu           653721 non-null  object
 47  Vəziyyəti                 653718 non-null  object
 48  Yeni                      653721 non-null  object
 49  Yerlərin sayı             487890 non-null  object
 50  Yürüş                     653721 non-null  object
 51  Ötürücü                   653721 non-null  object
 52  Şəhər                     653721 non-null  object
 53  car_details_id_y          653721 non-null  object
 54  car_rel_url               653721 non-null  object
 55  extra_info                653721 non-null  object
dtypes: float64(4), int64(4), object(48)
memory usage: 279.3+ MB

In [ ]:
df = df.drop(columns = ['id_x', 'car_rel_url_x', 'datetime_scrape', 'name', 'datetime_product', 'engine_displacement_unit', 'spare_parts','img_url', 'id_y', 'cars_id', 'car_rel_url_y', 'car_rel_url_y', 'datetime','description','owner_name','shop_name','phone', 'updated', 'day', 'hour', 'views','vin','car_details_id_x', 'Şəhər','car_details_id_y','car_rel_url','extra_info'])

In [ ]:
df.duplicated().sum()

np.int64(409458)

In [ ]:
df = df.drop_duplicates()

In [ ]:
len(df)

244263

In [ ]:
df['Yeni'] = df['Yeni'].apply(lambda x: 1 if x == 'Bəli' else 0)

In [ ]:
df['Yürüş'] = df['Yürüş'].str.replace('km','',regex = True)
df['Yürüş'] = df['Yürüş'].str.replace(' ','',regex = True)
df['Yürüş'] = df['Yürüş'].astype(int)

In [ ]:
df['Mühərrik']

0              1.6 L/115 a.g./Dizel
1              1.7 L/80 a.g./Benzin
2             4.0 L/282 a.g./Benzin
3             2.0 L/150 a.g./Benzin
4              1.5 L/76 a.g./Hibrid
                    ...
653715     1.6 L / 75 a.g. / Benzin
653716     1.5 L / 76 a.g. / Hibrid
653717    2.9 L / 135 a.g. / Benzin
653719    4.7 L / 258 a.g. / Benzin
653720    3.0 L / 400 a.g. / Benzin
Name: Mühərrik, Length: 244263, dtype: object

In [ ]:
df['kilometrage_unit']

0         km
1         km
2         km
3         km
4         km
          ..
653715    km
653716    km
653717    km
653719    km
653720    km
Name: kilometrage_unit, Length: 244263, dtype: object

In [ ]:
l = [i for i in df.columns]
l

['price_x',
 'currency_x',
 'city',
 'attributes',
 'production_year',
 'engine_displacement_num',
 'kilometrage_num',
 'kilometrage_unit',
 'barter',
 'loan',
 'salon',
 'vip',
 'featured',
 'price_y',
 'currency_y',
 'Ban növü',
 'Buraxılış ili',
 'Hansı bazar üçün yığılıb',
 'Marka',
 'Model',
 'Mühərrik',
 'Qəzalı',
 'Rəng',
 'Sahiblər',
 'Sürətlər qutusu',
 'Vəziyyəti',
 'Yeni',
 'Yerlərin sayı',
 'Yürüş',
 'Ötürücü']

In [ ]:
df.head()

,price_x,currency_x,city,attributes,production_year,engine_displacement_num,kilometrage_num,kilometrage_unit,barter,loan,...,Mühərrik,Qəzalı,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Yürüş,Ötürücü
0,15000.0,AZN,bakı,"2008, 1.6 L, 270 000 km",2008,1.6,270000,km,NaN,NaN,...,1.6 L/115 a.g./Dizel,NaN,Gümüşü,2,Mexaniki,"Vuruğu yoxdur, rənglənməyib",0,5,270000,Ön
1,23700.0,AZN,bakı,"2024, 1.7 L, 0 km",2024,1.7,0,km,NaN,NaN,...,1.7 L/80 a.g./Benzin,NaN,Yaşıl,NaN,Mexaniki,"Vuruğu yoxdur, rənglənməyib",1,5,0,Tam
2,35600.0,$,bakı,"2011, 4.0 L, 164 750 km",2011,4.0,164750,km,NaN,NaN,...,4.0 L/282 a.g./Benzin,NaN,Ağ,0,Avtomat,"Vuruğu yoxdur, rənglənməyib",0,8+,164750,Tam
3,26700.0,AZN,bakı,"2018, 2.0 L, 126 000 km",2018,2.0,126000,km,NaN,NaN,...,2.0 L/150 a.g./Benzin,NaN,Boz,1,Avtomat,"Vuruğu yoxdur, rənglənməyib",0,NaN,126000,Ön
4,10500.0,AZN,bakı,"2007, 1.5 L, 354 000 km",2007,1.5,354000,km,NaN,NaN,...,1.5 L/76 a.g./Hibrid,NaN,Qırmızı,2,Variator,"Vuruğu yoxdur, rənglənməyib",0,5,354000,Ön

In [ ]:
df['barter'] = df['barter'].apply(lambda x: 1 if x == 'Barter mümkündür' else 0)

In [ ]:
df['loan'] = df['loan'].apply(lambda x: 1 if x == 'Kreditdədir' else 0)

In [ ]:
df = df.drop(columns = 'attributes')

In [ ]:
df['salon'] = df['salon'].apply(lambda x: 1 if x == 'Salon' else 0)

In [ ]:
df['vip'] = df['vip'].apply(lambda x: 1 if x == 'vipped-icon' else 0)

In [ ]:
df['featured'] = df['featured'].apply(lambda x: 1 if x == 'featured-icon' else 0)

In [ ]:
df['kilometrage_unit is km'] = df['kilometrage_unit'].apply(lambda x:1 if x == 'km' else 0)
df = df.drop(columns = 'kilometrage_unit')

In [ ]:
df['Qəzalı'] = df['Qəzalı'].apply(lambda x: 1 if x == 'Bəli' else 0)

In [ ]:
df['Yerlərin sayı'] = df['Yerlərin sayı'].str.replace('+','')
df['Yerlərin sayı'] = df[df['Yerlərin sayı'].notna()]['Yerlərin sayı'].astype(int)

In [ ]:
df.dtypes

price_x                     float64
currency_x                   object
city                         object
production_year               int64
engine_displacement_num     float64
kilometrage_num               int64
barter                        int64
loan                          int64
salon                         int64
vip                           int64
featured                      int64
price_y                     float64
currency_y                   object
Ban növü                     object
Buraxılış ili                 int64
Hansı bazar üçün yığılıb     object
Marka                        object
Model                        object
Mühərrik                     object
Qəzalı                        int64
Rəng                         object
Sahiblər                     object
Sürətlər qutusu              object
Vəziyyəti                    object
Yeni                          int64
Yerlərin sayı               float64
Yürüş                         int64
Ötürücü                      object
kilometrage_unit is km        int64
dtype: object

In [ ]:
df['price_x'].isna().sum()

np.int64(0)

In [ ]:
df['price_y'].isna().sum()

np.int64(0)

In [ ]:
different_prices = df[df['price_x'] != df['price_y']]
different_prices[['price_x','price_y']]

        price_x  price_y
1413    18500.0  18000.0
3677    34700.0  35500.0
4604     8300.0   7800.0
7107    28500.0  28000.0
14813   22900.0  22400.0
...         ...      ...
643414   5700.0   6500.0
648019   6500.0   6000.0
649678  16500.0  16300.0
651590  17500.0  17000.0
653477  28900.0  28400.0

[298 rows x 2 columns]

In [ ]:
df = df.drop(columns = ['price_x','currency_x'])

In [ ]:
df.head()

,city,production_year,engine_displacement_num,kilometrage_num,barter,loan,salon,vip,featured,price_y,...,Qəzalı,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Yürüş,Ötürücü,kilometrage_unit is km
0,bakı,2008,1.6,270000,0,0,0,0,0,15000.0,...,0,Gümüşü,2,Mexaniki,"Vuruğu yoxdur, rənglənməyib",0,5.0,270000,Ön,1
1,bakı,2024,1.7,0,0,0,1,1,1,23700.0,...,0,Yaşıl,NaN,Mexaniki,"Vuruğu yoxdur, rənglənməyib",1,5.0,0,Tam,1
2,bakı,2011,4.0,164750,0,0,0,1,1,35600.0,...,0,Ağ,0,Avtomat,"Vuruğu yoxdur, rənglənməyib",0,8.0,164750,Tam,1
3,bakı,2018,2.0,126000,0,0,0,1,0,26700.0,...,0,Boz,1,Avtomat,"Vuruğu yoxdur, rənglənməyib",0,NaN,126000,Ön,1
4,bakı,2007,1.5,354000,0,0,0,1,0,10500.0,...,0,Qırmızı,2,Variator,"Vuruğu yoxdur, rənglənməyib",0,5.0,354000,Ön,1

In [ ]:
df.columns

Index(['city', 'production_year', 'engine_displacement_num', 'kilometrage_num',
       'barter', 'loan', 'salon', 'vip', 'featured', 'price_y', 'currency_y',
       'Ban növü', 'Buraxılış ili', 'Hansı bazar üçün yığılıb', 'Marka',
       'Model', 'Mühərrik', 'Qəzalı', 'Rəng', 'Sahiblər', 'Sürətlər qutusu',
       'Vəziyyəti', 'Yeni', 'Yerlərin sayı', 'Yürüş', 'Ötürücü',
       'kilometrage_unit is km'],
      dtype='object')

In [ ]:
df['Vəziyyəti'].unique()

array(['Vuruğu yoxdur, rənglənməyib', 'Vuruğu yoxdur, rənglənib',
       'Vuruğu var, rənglənib', 'Vuruğu var, rənglənməyib', nan],
      dtype=object)

In [ ]:
df['Sahiblər'] = df['Sahiblər'].str.replace(' və daha çox','',regex = True)
df['Sahiblər'] = df[df['Sahiblər'].notna()]['Sahiblər'].astype(int)

In [ ]:
df['Sahiblər']

0         2.0
1         NaN
2         0.0
3         1.0
4         2.0
         ...
653715    2.0
653716    2.0
653717    0.0
653719    2.0
653720    0.0
Name: Sahiblər, Length: 244263, dtype: float64

In [ ]:
df['Yanacaq novu'] = df['Mühərrik'].str.split('/').str[-1]

In [ ]:
df['Mühərrik']

0              1.6 L/115 a.g./Dizel
1              1.7 L/80 a.g./Benzin
2             4.0 L/282 a.g./Benzin
3             2.0 L/150 a.g./Benzin
4              1.5 L/76 a.g./Hibrid
                    ...
653715     1.6 L / 75 a.g. / Benzin
653716     1.5 L / 76 a.g. / Hibrid
653717    2.9 L / 135 a.g. / Benzin
653719    4.7 L / 258 a.g. / Benzin
653720    3.0 L / 400 a.g. / Benzin
Name: Mühərrik, Length: 244263, dtype: object

In [ ]:
df['price_y'] = np.where(df['currency_y'].isin(['USD', 'EUR']),
                       df['price_y'] * 1.7,
                       df['price_y'])

In [ ]:
df = df.drop(columns = 'currency_y')

In [ ]:
df['city'] = np.where(df['city'] == 'bakı',1,0)

In [ ]:
df

,city,production_year,engine_displacement_num,kilometrage_num,barter,loan,salon,vip,featured,price_y,...,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Yürüş,Ötürücü,kilometrage_unit is km,Yanacaq novu
0,1,2008,1.6,270000,0,0,0,0,0,15000.0,...,Gümüşü,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",0,5.0,270000,Ön,1,Dizel
1,1,2024,1.7,0,0,0,1,1,1,23700.0,...,Yaşıl,NaN,Mexaniki,"Vuruğu yoxdur, rənglənməyib",1,5.0,0,Tam,1,Benzin
2,1,2011,4.0,164750,0,0,0,1,1,60520.0,...,Ağ,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",0,8.0,164750,Tam,1,Benzin
3,1,2018,2.0,126000,0,0,0,1,0,26700.0,...,Boz,1.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",0,NaN,126000,Ön,1,Benzin
4,1,2007,1.5,354000,0,0,0,1,0,10500.0,...,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",0,5.0,354000,Ön,1,Hibrid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
653715,1,2008,1.6,63000,0,0,0,0,0,7750.0,...,Tünd qırmızı,2.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",0,4.0,63000,Arxa,1,Benzin
653716,1,2008,1.5,320000,1,0,0,0,0,10800.0,...,Qırmızı,2.0,Variator,"Vuruğu yoxdur, rənglənməyib",0,5.0,320000,Ön,1,Hibrid
653717,0,2011,2.9,155000,0,0,0,0,0,9500.0,...,Boz,0.0,Mexaniki,"Vuruğu yoxdur, rənglənməyib",0,NaN,155000,Tam,1,Benzin
653719,0,1999,4.7,250000,1,0,0,0,0,10600.0,...,Qara,2.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",0,5.0,250000,Tam,1,Benzin
653720,1,2023,3.0,19000,1,0,1,0,0,218450.0,...,Qara,0.0,Avtomat,"Vuruğu yoxdur, rənglənməyib",0,5.0,19000,Tam,1,Benzin

In [ ]:
df = df.drop(columns = 'kilometrage_num')

In [ ]:
df = df.drop(columns = 'kilometrage_unit is km')

In [ ]:
df = df.drop(columns = 'loan')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 244263 entries, 0 to 653720
Data columns (total 24 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   city                      244263 non-null  int64
 1   production_year           244263 non-null  int64
 2   engine_displacement_num   244263 non-null  float64
 3   barter                    244263 non-null  int64
 4   salon                     244263 non-null  int64
 5   vip                       244263 non-null  int64
 6   featured                  244263 non-null  int64
 7   price_y                   244263 non-null  float64
 8   Ban növü                  244263 non-null  object
 9   Buraxılış ili             244263 non-null  int64
 10  Hansı bazar üçün yığılıb  174528 non-null  object
 11  Marka                     244263 non-null  object
 12  Model                     244262 non-null  object
 13  Mühərrik                  244263 non-null  object
 14  Qəzalı                    244263 non-null  int64
 15  Rəng                      244263 non-null  object
 16  Sahiblər                  171359 non-null  float64
 17  Sürətlər qutusu           244263 non-null  object
 18  Vəziyyəti                 244260 non-null  object
 19  Yeni                      244263 non-null  int64
 20  Yerlərin sayı             183992 non-null  float64
 21  Yürüş                     244263 non-null  int64
 22  Ötürücü                   244263 non-null  object
 23  Yanacaq novu              244263 non-null  object
dtypes: float64(4), int64(10), object(10)
memory usage: 46.6+ MB

In [ ]:
df = df.drop(columns = 'Mühərrik')

In [ ]:
df.duplicated().sum()

np.int64(1037)

In [ ]:
df = df.drop_duplicates()

#Neural Networks

In [ ]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

In [ ]:
X = df.drop(columns = 'price_y')
y = df['price_y'].copy()

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    random_state = 42,
                                                    test_size = 0.2)

In [ ]:
num_col = X.select_dtypes(include= 'number').columns
cat_col = X.select_dtypes(include = 'object').columns

In [ ]:
num_pipeline = make_pipeline(
    SimpleImputer(strategy = 'median'),
    StandardScaler()
)

cat_pipeline = make_pipeline(
    SimpleImputer(strategy = 'most_frequent'),
    OneHotEncoder()
)

preprocessing = ColumnTransformer(
    transformers = [
        ('num', num_pipeline, num_col),
        ('cat', cat_pipeline, cat_col)
    ]
)

In [ ]:
X_train_transformed = preprocessing.fit_transform(X_train)
X_train_transformed = X_train_transformed.toarray()
pd.DataFrame(X_train_transformed,columns = preprocessing.get_feature_names_out())

,num__city,num__production_year,num__engine_displacement_num,num__barter,num__salon,num__vip,num__featured,num__Buraxılış ili,num__Qəzalı,num__Sahiblər,...,cat__Yanacaq novu_80 sm,cat__Yanacaq novu_800 sm,cat__Yanacaq novu_900 sm,cat__Yanacaq novu_Benzin,cat__Yanacaq novu_Dizel,cat__Yanacaq novu_Elektro,cat__Yanacaq novu_Hibrid,cat__Yanacaq novu_Hidrogen,cat__Yanacaq novu_Plug-in Hibrid,cat__Yanacaq novu_Qaz
0,0.572975,0.141265,-1.844771,1.625647,2.364911,1.767468,2.615936,1.210606,-0.072843,-0.392947,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,-1.745278,0.100980,-0.149592,1.625647,-0.422849,-0.565781,-0.382272,0.478319,-0.072843,-0.392947,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.572975,-0.060158,0.274203,-0.615140,-0.422849,-0.565781,-0.382272,-2.450829,-0.072843,-0.392947,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.572975,0.027125,-0.488628,-0.615140,-0.422849,-0.565781,-0.382272,-0.864207,-0.072843,0.967933,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-1.745278,0.080838,-0.319110,-0.615140,-0.422849,-0.565781,-0.382272,0.112176,-0.072843,-0.392947,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194575,0.572975,-0.006446,-0.488628,-0.615140,-0.422849,-0.565781,-0.382272,-1.474446,-0.072843,-0.392947,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
194576,-1.745278,0.121122,-0.149592,1.625647,-0.422849,1.767468,2.615936,0.844463,-0.072843,-0.392947,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
194577,-1.745278,0.040553,-0.149592,-0.615140,-0.422849,-0.565781,-0.382272,-0.620111,-0.072843,0.967933,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
194578,0.572975,0.040553,2.816971,1.625647,-0.422849,-0.565781,-0.382272,-0.620111,-0.072843,0.967933,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
194579,0.572975,0.060695,0.697998,-0.615140,-0.422849,-0.565781,-0.382272,-0.253968,-0.072843,0.967933,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
model = tf.keras.Sequential([
])

# Model Preparing

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import PolynomialFeatures
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from lightgbm import LGBMRegressor

In [ ]:
sampled_df = df.sample(n = 100_000, random_state = 42)

In [ ]:
sampled_df.duplicated().sum()

In [ ]:
X = sampled_df.drop(columns = 'price_y')
y = sampled_df['price_y'].copy()

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,
                                                 test_size = 0.2,
                                                 random_state = 42)

In [ ]:
num_columns = X.select_dtypes('number').columns
cat_columns = X.select_dtypes('object').columns

#Base model - Linear Regression

In [ ]:
num_pipeline = make_pipeline(
    StandardScaler(),
    SimpleImputer(strategy = 'median'),
    PolynomialFeatures(degree = 2)
)

cat_pipeline = make_pipeline(
    OneHotEncoder(handle_unknown = 'ignore'),
    SimpleImputer(strategy = 'most_frequent')
)

preprocessing = ColumnTransformer(
    transformers = [
        ('num',num_pipeline, num_columns),
        ('cat',cat_pipeline, cat_columns)
    ]
)

In [ ]:
lin_reg = LinearRegression()

full_pipeline_lin = make_pipeline(preprocessing,lin_reg)
full_pipeline_lin.fit(X_train,y_train)

In [ ]:
full_pipeline_lin.score(X_test,y_test)

In [ ]:
full_pipeline_lin.score(X_train,y_train)

In [ ]:
scores = cross_val_score(full_pipeline_lin, X, y, cv=3, scoring='r2',n_jobs = -1)

In [ ]:
np.mean(scores)

In [ ]:
y_pred = full_pipeline_lin.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mae

In [ ]:
y_pred = full_pipeline_lin.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
mse

# DecisionTree Regressor

In [ ]:
num_pipeline_dec = make_pipeline(
    SimpleImputer(strategy = 'median')
)

cat_pipeline_dec = make_pipeline(
    SimpleImputer(strategy = 'most_frequent'),
    OneHotEncoder(handle_unknown = 'ignore')
)

preprocessing_dec = ColumnTransformer(
    transformers = [
        ('num',num_pipeline_dec, num_columns),
        ('cat',cat_pipeline_dec, cat_columns)
    ]
)

In [ ]:
dec_tree = DecisionTreeRegressor(min_samples_split = 34,min_samples_leaf = 4,max_depth = 43)

full_pipeline_dec = make_pipeline(preprocessing_dec, dec_tree)
full_pipeline_dec.fit(X_train, y_train)

In [ ]:
full_pipeline_dec.score(X_test, y_test)

In [ ]:
full_pipeline_dec.score(X_train,y_train)

In [ ]:
param_dist = {
    "decisiontreeregressor__max_depth": np.random.randint(1, 51, size=10),
    "decisiontreeregressor__min_samples_split": np.random.randint(2, 51, size=10),
    "decisiontreeregressor__min_samples_leaf": np.random.randint(1, 21, size=10)
}

# RandomizedSearch tətbiq et
random_search = RandomizedSearchCV(
    full_pipeline_dec,
    param_distributions=param_dist,
    n_iter=50,
    scoring="r2",
    cv=3,
    verbose=2,
    n_jobs=-1,
    random_state=42
)

random_search.fit(X_train,y_train)

In [ ]:
random_search.best_params_

In [ ]:
random_search.best_score_

In [ ]:
scores = cross_val_score(full_pipeline_dec, X, y, cv=3, scoring='r2')
np.mean(scores)

In [ ]:
y_pred = full_pipeline_dec.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mae

In [ ]:
y_pred = full_pipeline_dec.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
mse

# LightGBM Regressor - Best Model

In [ ]:
lgbm_reg = LGBMRegressor(
    n_estimators=500,
    force_row_wise=True,
    verbosity=0,
    learning_rate=0.05,
    max_depth=-1,
    random_state=42
)


full_pipeline_lgbm = make_pipeline(preprocessing, lgbm_reg)
full_pipeline_lgbm.fit(X_train, y_train)

In [ ]:
full_pipeline_lgbm.score(X_train, y_train)

In [ ]:
full_pipeline_lgbm.score(X_test, y_test)

In [ ]:
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

scores = cross_val_score(full_pipeline_lgbm, X, y, cv=3, scoring='r2')
np.mean(scores)

In [ ]:
y_pred = full_pipeline_lgbm.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mae

In [ ]:
full_pipeline_lgbm.predict()